apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: personalpage
    namespace: bregy
    annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: buypass
spec:
    tls:
        - hosts:
              - bregy.minsky.cc
          secretName: bregy.minsky.cc-cert
    rules:
        - host: bregy.minsky.cc
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: personalpage
                        servicePort: web

---
kind: Service
apiVersion: v1
metadata:
    name: personalpage
    namespace: bregy
spec:
    selector:
        app: personalpage
    type: ClusterIP
    ports:
        - name: web
          port: 80
          targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: landpersonalpageing
    namespace: bregy
    labels:
        app: personalpage
spec:
    replicas: 1
    selector:
        matchLabels:
            app: personalpage
    template:
        metadata:
            name: personalpage
            labels:
                app: personalpage
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: personalpage
                  image: docker.minsky.cc/bregy
                  imagePullPolicy: Always
            restartPolicy: Always
